# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170710_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 11, 13, 57, 47, 139559)),
        ),
    ]
